#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- PCM4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cleancase is function that removes the files and directories.(rm -f : remove the file, rm -r : remove the directory).
cleancase ()
{
    rm -r Gnu*
    rm -r processor*
}

# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

cleancase
#./Allclean

echo run blockMesh ...
m4 -P constant/polyMesh/blockMeshDictVerticalConicalCylinder.m4 > constant/polyMesh/blockMeshDict
blockMesh

echo run solver ...
#$application
simple4PCMFoam

# ----------------------------------------------------------------- end-of-file






