#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -f 0/cellToRegion*
rm -rf 0/chamber
rm -rf 0/square
rm -f constant/cellToRegion*
rm -rf constant/polyMesh/boundary
rm -rf constant/chamber/polyMesh
rm -rf constant/square/polyMesh
rm -rf constant/polyMesh/blockMeshDict
rm -rf VTK
rm -rf dynamicCode
rm -f post*


