#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
cleanCase
rm -f constant/polyMesh/boundary
rm -f postProcess.txt
rm -r dynamicCode
cp 0/alpha1.org 0/alpha1
cp 0/T.org 0/T

