#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- PCM4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cleancase is function that removes the files and directories.(rm -f : remove the file, rm -r : remove the directory).
cleancase ()
{
    rm -r Gnu*
    rm -r processor*
}

# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
#application=$(getApplication)
application="interFoam4PCMFoam"

#cleancase
#./Allclean

echo run blockMesh ...
blockMesh

echo run solver ...
setFields
changeDictionary
$application
streamFunction
