#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -f constant/polyMesh/boundary
rm -f constant/polyMesh/blockMeshDict
rm -f post*
rm -r dynamicCode
