#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -f 0/cellToRegion*
rm -rf 0/miniChannel
rm -rf 0/cast
rm -f constant/cellToRegion*
rm -rf constant/polyMesh/boundary
rm -rf constant/miniChannel/polyMesh
rm -rf constant/polyMesh/blockMeshDict
rm -rf constant/cast
rm -rf VTK
rm -rf postProcess.txt
rm -rf dynamicCode

