#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -f constant/polyMesh/boundary
rm -f constant/polyMesh/refinementHistory*
rm -f constant/polyMesh/blockMeshDict
rm -f constant/cellLevel*
rm -f constant/pointLevel*
rm -f constant/triSurface/cylinderSc.stl
rm -f constant/triSurface/cylinder.stl
rm -f constant/triSurface/cylinder.fms
rm -r dynamicCode
rm -f postProcess.txt
