#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

#------------------------------- PCM4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

rm -r `find . -name linux*`
rm -r `find . -name lnInclude*`
rm `find . -name *.dep`

# -------------------------------------------------------------------------- end-of-file
