#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/polyMesh/blockMeshDict
rm -f 0/cellToRegion*
rm -rf 0/chamber
rm -rf 0/leftSolid
rm -rf 0/rightSolid
rm -f constant/cellToRegion*
rm -rf constant/polyMesh/boundary
rm -rf constant/chamber/polyMesh
rm -rf constant/leftSolid
rm -rf constant/rightSolid
rm -rf VTK

