#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/polyMesh/blockMeshDict
rm -f 0/cellToRegion*
rm -rf 0/hollow
rm -rf 0/block
rm -f constant/cellToRegion*
rm -rf constant/polyMesh/boundary
rm -rf constant/hollow/polyMesh
rm -rf constant/block/polyMesh
rm -rf VTK
rm -rf dynamicCode
rm blockPostProcess.txt
