#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- PCM4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cleancase is function that removes the files and directories.(rm -f : remove the file, rm -r : remove the directory).
cleancase ()
{
    rm -r Gnu*
    rm -r processor*
}


# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

#cleancase
#./Allclean


echo run blockMesh ...
m4 -P constant/polyMesh/blockMeshDictTrapezoid.m4 > constant/polyMesh/blockMeshDict
blockMesh

setSet -batch hollow.setSet
rm constant/polyMesh/sets/*_old
rm constant/polyMesh/sets/*_old.gz
setsToZones -noFlipMap
splitMeshRegions -cellZones -overwrite

mkdir -p 0.001/hollow
mkdir -p 0.001/block

cp 0/* 0.001/hollow/
cp 0/* 0.001/block/

changeDictionary -region hollow
changeDictionary -region block


echo run solver ...
#$application
chtMultiRegion4PCMFoam

# -------------------------------------------------------------------------- end-of-file






